### ISSUE TITLE
Should our first chocolatey release be v1.1.0?

### ISSUE THREAD

**Issue by jackdevey** [BanDev/Lux#21]
Should our first chocolatey release be v1.1.0, do you think?

_Originally posted by @russellbanks in https://github.com/BanDev/Lux/issues/16#issuecomment-975892632_

**Comment by russellbanks** [comment]
I feel like seeing as v1.1.0 has an x86 variation as well as an x64 variation, this would be ideal to be our first release on chocolatey.

**Comment by jackdevey** [comment]
yea u already sed u looney
