### ISSUE TITLE
Govee RGBIC model H6147

### ISSUE THREAD

**Issue by andurox** [BanDev/Lux#24]
Govee RGBIC model H6147 How do I make it work?

**Comment by russellbanks** [comment]
Hey,

I'm afraid that the Govee RGBIC Model H6147 does not support WiFi, and therefore is unable to utilise the Govee API, which Lux uses.

According to the [Govee website for the H6147 mode](https://us.govee.com/products/govee-rgbic-led-strip-lights-65-6ft)l, it is controlled via `Bluetooth + App Control`, and does not specify WiFi functionality.

Likewise, in the product description for the model on [Amazon](https://www.amazon.com/Govee-Changing-Bluetooth-Segmented-Multiple/dp/B08QJ5BQ1T/ref=sr_1_5?keywords=govee%2Bh6147&qid=1638467622&sr=8-5&th=1), it states:

> Connect Method: **Only support Bluetooth app control, do not support WiFi connect**, Alexa and Google assistant.
True Segmented Color Control: Each color changing led lights is divided into 15 segments which can be controlled individually. Create your own lighting design and creative DIY in the Govee Home app (**Only Bluetooth control, do not support WiFi connect**).
