### ISSUE TITLE
lux color command entered as show in example gives error "Not enough arguments required"

### ISSUE THREAD

**Issue by BeauBreeden** [BanDev/Lux#27]
For a device that returns the following information with the `lux devices complex`:
```
DEVICE 0
  MAC Address:    E1:18:D4:AD:FC:32:23:92
  Model:          H6008
  Name:           East bulb
  Controllable:   [✓ Yes]
  Retrievable:    [✓ Yes]
  Commands:       turn, brightness, color, colorTem
```

This error is given following the shown command:
```
lux color 0 #ff0000
Not enough arguments required. E.g. lux color 0 #0067f4
```

The command used is taken right from the examples shown after `lux help`.

I can't determine any error on my part, and other commands such as `lux turn 0 on/off` and `lux  brightness 0/00` works as expected.

```
lux help
Welcome to Lux!
Lux v1.1.0
```

Is there something I'm missing?

**Comment by russellbanks** [comment]
Hey, @jackdevey is the developer that works on Lux the most (and wrote its codebase). I've pinged him to see what's wrong here because from what I can see, that looks like valid syntax.

**Comment by jackdevey** [comment]
I think this is an issue regarding how the command is parsed with Powershell. For some reason, it doesn't properly read the hexadecimal colour code argument because of the leading `#`. 

I will definitely look into it but in the meantime you can wrap the colour in speech marks to force Powershell to consider the argument a string. Something like:
```
lux color 0 "#ff0000"
```
Or you could use command prompt as this seems to work fine without the speech marks.

**Comment by jackdevey** [comment]
https://ss64.com/ps/syntax-esc.html
Yeah it looks like `#` is used to denote the beginning of a comment, so the colour code was just being outright removed by Powershell and never being passed to lux as an argument. I'll remove the requirement for colour codes to begin with `#` in Lux

**Comment by BeauBreeden** [comment]
> I think this is an issue regarding how the command is parsed with Powershell. For some reason, it doesn't properly read the hexadecimal colour code argument because of the leading `#`.
> 
> I will definitely look into it but in the meantime you can wrap the colour in speech marks to force Powershell to consider the argument a string. Something like:
> 
> ```
> lux color 0 "#ff0000"
> ```
> 
> Or you could use command prompt as this seems to work fine without the speech marks.

This is exactly the issue, and I'm a little ashamed it didnt cross my mind that the # needed to be escaped. For notes, you can either wrap the rgb hex in quotes, or escape the # with a `.

**Comment by jackdevey** [comment]
> This is exactly the issue, and I'm a little ashamed it didnt cross my mind that the # needed to be escaped. For notes, you can either wrap the rgb hex in quotes, or escape the # with a `.

Aha same here, I have made it optional so you can escape them or just not include them. Just need @russellbanks to approve my merge and then I will look into making a minor release to implement the fix.

**Comment by jackdevey** [comment]
Just to let you know the new update is out on winget
```
winget upgrade BanDev.Lux
```
Or, you can download it [here](https://github.com/BanDev/Lux/releases/tag/v1.1.1)
